"""The gazetteer's hand-authored side for Middle-earth.

The ME-GIS place layer carries 785 label points, most of them canon and some
from the role-playing supplements the ME-DEM team drew on. What it does not
carry is the second name everything in Tolkien has — Imladris for Rivendell,
the Lonely Mountain for Erebor — nor a few places a reader is certain to ask
for, which the layer has no point for. Both live here.

Coordinates in EXTRA are ME-GIS map kilometres, as in `me_regions.py`.
"""

# label as it appears in the layer -> what the gazetteer should call it
RENAME = {
    "Shire": "The Shire",
    "Trollsahws": "Trollshaws",
    "Lossanarch": "Lossarnach",
    "Lebenin": "Lebennin",
    "Rhun": "Rhûn",
    "Fanouidhol": "Fanuidhol",
    "Khazad Dûm": "Khazad-dûm",
    "Mt Doom": "Mount Doom",
    "Henneth Arnen": "Henneth Annûn",
    "Morannon Gate": "Morannon",
    "Gram": "Mount Gram",
    "Fornost Erain": "Fornost",
    "Iach Sarn": "Sarn Ford",
    "Iant Methed": "Last Bridge",
    "Athrad Poros": "Crossings of Poros",
    "Iach Celduin": "Ford of Celduin",
    "Halls of the Elven King": "Halls of Thranduil",
}

# name -> aliases, "|"-separated as the gazetteer stores them
ALIASES = {
    "Rivendell": "Imladris|Last Homely House",
    "Erebor": "Lonely Mountain|The Lonely Mountain",
    "Khazad-dûm": "Moria|Mines of Moria|Dwarrowdelf",
    "Mithlond": "Grey Havens|The Grey Havens",
    "Fornost": "Fornost Erain|Norbury|Deadmen's Dike",
    "Minas Tirith": "Minas Anor|Mundburg|City of Kings",
    "Minas Ithil": "Minas Morgul|Tower of the Moon",
    "Isengard": "Orthanc|Angrenost",
    "Helm's Deep": "Hornburg|Helms Deep|The Hornburg",
    "Edoras": "Meduseld|Golden Hall",
    "Esgaroth": "Lake-town|Laketown|Lake Town",
    "Weathertop": "Amon Sûl|Amon Sul",
    "Lórien": "Lothlórien|Lothlorien|Golden Wood|Laurelindórenan",
    "Mirkwood": "Greenwood|Greenwood the Great|Eryn Lasgalen|Taur-nu-Fuin",
    "Hobbiton": "Bag End|Bagshot Row",
    "Barad-dûr": "Dark Tower|The Dark Tower|Lugbúrz",
    "Morannon": "Black Gate|The Black Gate|Morannon Gate",
    "Gundabad": "Mount Gundabad",
    "Ered Luin": "Blue Mountains|The Blue Mountains",
    "Ered Nimrais": "White Mountains|The White Mountains",
    "Ered Mithrin": "Grey Mountains|The Grey Mountains",
    "Ered Lithui": "Ash Mountains|Mountains of Ash",
    "Ephel Duath": "Mountains of Shadow|Ephel Dúath",
    "Misty Mountains": "Hithaeglir|The Misty Mountains",
    "Fangorn": "Fangorn Forest|Entwood",
    "Halls of Thranduil": "Thranduil's Halls|Woodland Realm|Elvenking's Halls|Halls of the Elven King",
    "Rauros": "Falls of Rauros",
    "Erech": "Stone of Erech|Hill of Erech",
    "Mount Doom": "Orodruin|Amon Amarth|Mt Doom",
    "Goblin Gate": "Goblin-town|Goblin Town",
    "Sarn Ford": "Iach Sarn|Fords of Baranduin",
    "Last Bridge": "Bridge of Mitheithel|Iant Methed",
    "Crossings of Poros": "Athrad Poros|Poros crossing",
    "Dale": "Kingdom of Dale",
    "Umbar": "Havens of Umbar|City of the Corsairs",
    "Caras Galadhon": "City of the Trees",
    "Dol Guldur": "Hill of Sorcery",
    "Carn Dûm": "Carn Dum",
    "The Shire": "Shire|Sûza",
    "Old Forest": "The Old Forest",
    "High Pass": "Pass of Imladris|Cirith Forn en Andrath",
    "Fords of Isen": "Isen fords|Ford of Isen",
    "Long Lake": "Lake of Esgaroth",
    "Nen Hithoel": "Lake of Nen Hithoel",
    "Argonath": "Pillars of the Kings|Gate of Kings",
    "Dead Marshes": "The Dead Marshes",
    "Rhûn": "Rhun|The East",
    "Gorgoroth": "Plateau of Gorgoroth",
    "Udûn": "Udun",
    "Dagorlad": "Battle Plain",
    "Dunland": "Dunlending country",
    "Eriador": "The Lone-lands",
    "Grey Havens": "Mithlond harbour",
    "Rhosgobel": "Radagast's house",
    "Annúminas": "Annuminas",
    "Osgiliath": "Citadel of the Stars",
    "Pelargir": "Garth of Royal Ships",
    "Dol Amroth": "Dol Amroth castle",
    "Tharbad": "Tharbad bridge",
    "Bree": "Bree-town|Prancing Pony",
    "Michel Delving": "Michel Delving on the White Downs",
    "Iron Hills": "Emyn Engrin",
    "Wold": "The Wold|Wold of Rohan",
    "Brown Lands": "The Brown Lands",
    "Carrock": "The Carrock",
}

# (name, x_km, y_km, kind, rank, aliases) — kind codes as in the gazetteer
EXTRA = [
    ("Gondor",            1000, 600, "g", 0, "Kingdom of Gondor|South Kingdom"),
    ("Lindon",             250, 1050, "g", 0, ""),
    ("Ithilien",          1140, 620, "g", 0, "Garden of Gondor"),
    ("Forodwaith",         700, 1550, "g", 0, "Northern Waste|Northern Wastes"),
    ("Harad",             1150, 300, "g", 0, "The South|Sunlands"),
    ("Near Harad",        1150, 360, "g", 0, ""),
    ("Forochel",           600, 1460, "g", 0, "Cape of Forochel|Icebay of Forochel"),
    ("Angmar",             800, 1290, "g", 0, "Witch-realm of Angmar"),
    ("Dunharrow",          850, 702, "k", 250000, "Hold of Dunharrow|Firienfeld"),
    ("Pelennor Fields",   1122, 625, "n", 0, "Pelennor|Fields of Pelennor"),
    ("Amon Hen",          1076, 746, "k", 3000, "Hill of Sight|Seat of Seeing"),
    ("Parth Galen",       1078, 751, "n", 0, ""),
    ("Beorn's Hall",      1046, 1082, "t", 20000, "Beorn's house|Beorn's House"),
    ("Doors of Durin",     851, 918, "k", 3000, "West-gate of Moria|Hollin Gate|Gate of Moria"),
    ("Ford of Bruinen",    877, 1056, "d", 0, "Bruinen ford|Ford of Rivendell"),
    ("Crickhollow",        556, 1030, "t", 6000, ""),
    ("Bucklebury Ferry",   551, 1030, "d", 0, "The Ferry"),
    ("Cross-roads of the Fallen King", 1165, 602, "d", 0, "Cross-roads|Crossroads of the Fallen King"),
    ("Cirith Gorgor",     1183, 720, "s", 0, "Haunted Pass"),
    ("Isenmouthe",        1200, 694, "s", 0, "Carach Angren"),
    ("Sammath Naur",      1231, 668, "k", 2000, "Chambers of Fire|Cracks of Doom"),
    ("Redhorn Pass",       875, 938, "s", 0, "Redhorn Gate|Pass of Caradhras|Caradhras pass"),
    ("Gap of Rohan",       800, 790, "s", 0, "The Gap|Gap of Isen"),
    ("Entwash mouths",    1060, 715, "m", 0, "Mouths of Entwash"),
    ("Mouths of Anduin",   995, 490, "o", 0, "Ethir Anduin|Anduin delta"),
    ("Cape of Andrast",    460, 440, "o", 0, "Ras Morthil"),
    ("Grey Wood",         1050, 660, "f", 0, "Firien Wood"),
    ("Drúadan Forest",    1094, 653, "f", 0, "Druadan Forest|Tawar-in-Drúedain"),
    ("Lake Evendim",       527, 1130, "w", 0, "Nenuial|Evendim"),
    ("Bywater Pool",       526, 1043, "w", 0, ""),
    ("Sea of Núrnen",     1400, 547, "w", 0, "Nurnen|Lake Núrnen|Sea of Nurnen"),
    ("Sea of Rhûn",       1561, 878, "w", 0, "Sea of Rhun|Inland Sea"),
    ("Bay of Belfalas",    820, 325, "o", 0, "Belfalas bay"),
]
